spring:
  rsocket:
    server:
      port: 7007
      transport: websocket
  cassandra:
    keyspace-name: test
    port: 9042
    local-datacenter: ap-northeast-2
    contact-points: scylla-db-client.scylla.svc.cluster.local


app:
  kafka:
    servers: kafka-headless.kafka.svc.cluster.local:9092
  aws:
    region: ap-northeast-2
    bucket-name: bsc-assets-public
    upload-expiration: 100000 #100 Seconds
  firebase-token: ${GOOGLE_FIREBASE_TOKEN}
  app-tokens:
    secret: thisisverysecretkeysoshouldreplaced
    refreshTokenValidity: 86400
    accessTokenValidity: 3600
  webclients:
    apple-oauth:
      baseUrl: https://appleid.apple.com/
    kakao-oauth:
      baseUrl: https://kapi.kakao.com/
    google-oauth:
      baseUrl: https://openidconnect.googleapis.com/
logging:
  level:
    org:
      apache:
        kafka: off
