name: ArgoCD로 배포하기
on:
  workflow_call:
    inputs:
      argocd-repo-name: #'CChuYong/bsc-argocd-manifest'
        required: true
        type: string
      overlay-name:
        required: true
        type: string
      service-name:
        required: true
        type: string
      image-url:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    name: ArgoCD로 배포하기

    environment: ${{ inputs.environment }}

    steps:
      - name: GitHub 에서 레포 받아오기
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.argocd-repo-name }}

      - name: Kustomize 설정하기
        uses: imranismail/setup-kustomize@v2

      - name: 이미지 태그 변경 후 배포하기
        run: |
          cd ${{ inputs.service-name }}/overlays/${{ inputs.overlay-name }}
          kustomize edit set image ${{ inputs.image-url }}
          cat kustomization.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "release(${{ inputs.service-name }}): 자동배포 ${{ github.sha }}"
          git push -u origin main

      - name: GitHub 에 릴리즈 태그 생성하기
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.service-name }}:${{ github.sha }}
          name: ${{ inputs.service-name }}:${{ github.sha }}
          body: "${{ inputs.image-url }}"
          commit: ${{ github.sha }}